name: pizza_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4
  intl_phone_field2: ^3.3.4
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.5.3
  flutter_geocoder: ^0.2.2-nullsafety
  http: ^1.2.0
  uuid: ^4.3.3
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.0.0
  location: ^6.0.2
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
  - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100  